const PLAN_KEY="vinmatPlansV2",CSV_KEY="vinmatCsvV2",THEME_KEY="vinmatThemeV1";
const AUTO_CSV_SOURCES=["../assets/data/bludiste.csv","../assets/data/omalovanky.csv","../assets/data/spojovacky.csv","../assets/data/obtahovacky.csv","../assets/data/dokreslovacky.csv","../assets/data/okruhy.csv"];
const ACTIVITIES=[
{id:"mazes",name:"Bludiště",emoji:"🧩",color:"#2563eb",files:["bludiste","maze"]},
{id:"coloring",name:"Omalovánky",emoji:"🎨",color:"#ef4444",files:["omalovanky","coloring","colouring"]},
{id:"dot",name:"Spojovačky",emoji:"🔢",color:"#f59e0b",files:["spojovacky","dot-to-dot","dot_to_dot"]},
{id:"tracing",name:"Obtahovačky",emoji:"✏️",color:"#16a34a",files:["obtahovacky","tracing"]},
{id:"drawing",name:"Dokreslovačky",emoji:"🖍️",color:"#8b5cf6",files:["dokreslovacky","complete"]},
{id:"tracks",name:"Čmárací okruhy",emoji:"🏎️",color:"#06b6d4",files:["okruhy","tracks","race"]}
];
let plans=readJSON(PLAN_KEY,{}),csvFiles=readJSON(CSV_KEY,[]),kind="week",cursor=new Date(),editing=false,weekEndOffset=25,monthEndOffset=29;
let weeklyVisible=new Set(ACTIVITIES.map(a=>a.id)),monthlyVisible=new Set(ACTIVITIES.map(a=>a.id));
let weeklyMode="stacked",monthlyMode="stacked";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}function save(){localStorage.setItem(PLAN_KEY,JSON.stringify(plans));localStorage.setItem(CSV_KEY,JSON.stringify(csvFiles))}
function norm(v){return String(v??"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-")}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function dateISO(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10)}
function monday(d){let x=new Date(d.getFullYear(),d.getMonth(),d.getDate()),day=x.getDay()||7;x.setDate(x.getDate()-day+1);return x}
function addDays(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}function addMonths(d,n){let x=new Date(d);x.setMonth(x.getMonth()+n);return x}
function isoWeek(d){let x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));let y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/86400000)+1)/7)}
function periodInfo(k,d){d=new Date(d);let s,e,title,key;if(k==="week"){s=monday(d);e=addDays(s,6);let wy=addDays(s,3).getFullYear(),w=isoWeek(s);title=`${w}. týden ${wy}`;key=`week:${dateISO(s)}`}else if(k==="month"){s=new Date(d.getFullYear(),d.getMonth(),1);e=new Date(d.getFullYear(),d.getMonth()+1,0);title=s.toLocaleDateString("cs-CZ",{month:"long",year:"numeric"});title=title[0].toUpperCase()+title.slice(1);key=`month:${s.getFullYear()}-${String(s.getMonth()+1).padStart(2,"0")}`}else if(k==="half"){let h=d.getMonth()<6?1:2;s=new Date(d.getFullYear(),h===1?0:6,1);e=new Date(d.getFullYear(),h===1?6:12,0);title=`${h}H ${d.getFullYear()}`;key=`half:${d.getFullYear()}-${h}`}else{s=new Date(d.getFullYear(),0,1);e=new Date(d.getFullYear(),11,31);title=String(d.getFullYear());key=`year:${d.getFullYear()}`}return{kind:k,start:s,end:e,title,key}}
function shiftPeriod(k,d,n){if(k==="week")return addDays(d,n*7);if(k==="month")return addMonths(d,n);if(k==="half")return addMonths(d,n*6);return new Date(d.getFullYear()+n,d.getMonth(),1)}
function activityForFile(name){let n=norm(name);return ACTIVITIES.find(a=>a.files.some(f=>n.includes(norm(f))))||{id:n,name:name.replace(/\.csv$/i,""),emoji:"📄",color:"#64748b",files:[]}}
function splitLines(t){let out=[],cur="",q=false;for(let i=0;i<t.length;i++){let c=t[i];if(c==='"'){cur+=c;if(q&&t[i+1]==='"')cur+=t[++i];else q=!q}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&t[i+1]==='\n')i++;if(cur.trim())out.push(cur);cur=""}else cur+=c}if(cur.trim())out.push(cur);return out}
function parseLine(l,d){let a=[],c="",q=false;for(let i=0;i<l.length;i++){let x=l[i];if(x==='"'){if(q&&l[i+1]==='"'){c+='"';i++}else q=!q}else if(x===d&&!q){a.push(c.trim());c=""}else c+=x}a.push(c.trim());return a}
function parseCSV(t){t=t.replace(/^\uFEFF/,"");let lines=splitLines(t);if(!lines.length)return[];let first=lines[0],opts=[",",";","\t"],d=opts.sort((a,b)=>first.split(b).length-first.split(a).length)[0],h=parseLine(first,d);return lines.slice(1).map(l=>{let v=parseLine(l,d),r={};h.forEach((x,i)=>r[x.trim()||`col${i}`]=v[i]??"");return r}).filter(r=>Object.values(r).some(v=>String(v).trim()))}
function col(row,names){let ks=Object.keys(row),nn=names.map(norm);return ks.find(k=>nn.some(n=>norm(k)===n||norm(k).includes(n)))}
function rowDate(row){let k=col(row,["datumPridani","datum","dateAdded","createdAt","date"]);if(!k)return null;let d=new Date(String(row[k]).trim()+"T12:00:00");return isNaN(d)?null:d}
function rowLevel(row){let k=col(row,["level","uroven","difficulty"]);if(k){let m=String(row[k]).match(/[1-5]/);if(m)return +m[0]}k=col(row,["soubor","filename","file","slug"]);if(k){let m=String(row[k]).match(/^lv([1-5])(?:[_-]|$)/i)||String(row[k]).match(/(?:^|[_-])lv([1-5])(?:[_-]|$)/i);if(m)return +m[1]}return null}
function rowMotif(row){let k=col(row,["ID","id","motiv","motif","nazevCz","name","title","slug"]);return k?String(row[k]).trim():""}
function allItems(){let out=[];csvFiles.forEach(f=>f.rows.forEach(r=>out.push({activity:f.activity,date:rowDate(r),level:rowLevel(r),motif:rowMotif(r)})));return out}
function counts(info){let c=Object.fromEntries(ACTIVITIES.map(a=>[a.id,0]));allItems().forEach(i=>{if(i.date&&i.date>=info.start&&i.date<=new Date(info.end.getFullYear(),info.end.getMonth(),info.end.getDate(),23,59,59)){if(c[i.activity.id]!==undefined)c[i.activity.id]++}});return c}
function total(o){return Object.values(o).reduce((a,b)=>a+(+b||0),0)}function pct(done,plan){return plan?Math.round(done/plan*100):null}
function renderPlanner(){let p=periodInfo(kind,cursor),actual=counts(p),saved=plans[p.key];$("#periodTitle").textContent=p.title;$("#periodDates").textContent=`${p.start.toLocaleDateString("cs-CZ")} – ${p.end.toLocaleDateString("cs-CZ")}`;$("#heroLabel").textContent=`Splnění: ${p.title}`;let values=saved?.values||Object.fromEntries(ACTIVITIES.map(a=>[a.id,0]));$("#plannerRows").innerHTML=ACTIVITIES.map(a=>{let pl=+values[a.id]||0,ac=actual[a.id]||0,pc=pct(ac,pl),vis=Math.min(100,pc||0);return`<tr><td class="activity">${a.emoji} ${a.name}</td><td><input class="num plan-input" data-id="${a.id}" type="number" min="0" value="${pl}" ${saved&&!editing?"disabled":""}></td><td><strong>${ac}</strong></td><td><div class="progress-line"><div class="track"><div class="fill" style="width:${vis}%"></div></div><strong>${pc===null?"—":pc+" %"}</strong></div></td></tr>`}).join("");let ps=total(values),as=total(actual),pc=saved?pct(as,ps):null;$("#heroPct").textContent=pc===null?"—":`${pc} %`;$("#donutPct").textContent=pc===null?"—":`${pc} %`;$("#donut").style.setProperty("--v",Math.min(100,pc||0));$("#heroBar").style.width=`${Math.min(100,pc||0)}%`;$("#heroMotivation").textContent=motivation(saved,as,ps,pc);$("#planStatus").className="status"+(saved?" saved":"");$("#planStatus").textContent=saved?`✅ Plán uložen ${new Date(saved.savedAt).toLocaleString("cs-CZ")}. Publikováno se načítá z CSV.`:"Bez stanoveného plánu. Publikované aktivity se přesto počítají.";$("#savePlan").textContent=saved?"Uložit změny":"Nastavit plán";$("#savePlan").classList.toggle("hidden",!!saved&&!editing);$("#editPlan").classList.toggle("hidden",!saved||editing);$("#cancelEdit").classList.toggle("hidden",!editing);renderArchive()}
function motivation(saved,d,p,pc){if(!saved)return"Pro toto období zatím není stanovený plán.";if(!p)return"Plán je uložený bez cílových hodnot.";if(d>p)return`Jsi o ${d-p} aktivit před plánem. Výborně!`;if(d===p)return"Plán je splněný. Skvělá práce! 🎉";let r=p-d;if(pc>=80)return`Cíl je blízko. Zbývá ${r} aktivit.`;if(pc>=50)return`Jsi za polovinou. Zbývá ${r} aktivit.`;return`Publikováno ${d} z plánovaných ${p} aktivit.`}
function saveCurrentPlan(){let p=periodInfo(kind,cursor),v={};$$('.plan-input').forEach(i=>v[i.dataset.id]=Math.max(0,Math.round(+i.value||0)));plans[p.key]={kind,start:dateISO(p.start),end:dateISO(p.end),title:p.title,values:v,savedAt:new Date().toISOString()};editing=false;save();renderPlanner()}
function archivePeriods(k){let items=allItems().filter(i=>i.date),starts=[];if(!items.length)return[];let min=new Date(Math.min(...items.map(i=>i.date))),now=new Date(),d;if(k==="week"){d=monday(min);let end=monday(now);while(d<=end){starts.push(new Date(d));d=addDays(d,7)}}else if(k==="month"){d=new Date(min.getFullYear(),min.getMonth(),1);let end=new Date(now.getFullYear(),now.getMonth(),1);while(d<=end){starts.push(new Date(d));d=addMonths(d,1)}}else if(k==="half"){d=new Date(min.getFullYear(),min.getMonth()<6?0:6,1);let end=new Date(now.getFullYear(),now.getMonth()<6?0:6,1);while(d<=end){starts.push(new Date(d));d=addMonths(d,6)}}else{d=new Date(min.getFullYear(),0,1);while(d.getFullYear()<=now.getFullYear()){starts.push(new Date(d));d=new Date(d.getFullYear()+1,0,1)}}return starts.reverse().slice(0,k==="week"?30:60).map(x=>periodInfo(k,x))}
function renderArchive(){let k=$("#archiveKind").value,periods=archivePeriods(k);$("#archiveRows").innerHTML=periods.map(p=>{let saved=plans[p.key],ac=total(counts(p)),pl=saved?total(saved.values):null,pc=saved?pct(ac,pl):null;return`<tr><td><strong>${p.title}</strong><br><small>${p.start.toLocaleDateString("cs-CZ")}–${p.end.toLocaleDateString("cs-CZ")}</small></td><td>${saved?pl:"—"}</td><td>${ac}</td><td>${pc===null?"—":pc+" %"}</td><td><span class="badge ${saved?"plan":"none"}">${saved?"Plán uložen":"Bez stanoveného plánu"}</span></td></tr>`}).join("")||'<tr><td colspan="5">Zatím nejsou dostupná historická data.</td></tr>'}
function renderStats(){if(!csvFiles.length){$("#statsEmpty").classList.remove("hidden");$("#statsContent").classList.add("hidden");renderPlanner();return}$("#statsEmpty").classList.add("hidden");$("#statsContent").classList.remove("hidden");let items=allItems(),groups={};ACTIVITIES.forEach(a=>groups[a.id]={...a,total:0,levels:[0,0,0,0,0,0]});let motifs=new Set();items.forEach(i=>{if(groups[i.activity.id]){groups[i.activity.id].total++;if(i.level)groups[i.activity.id].levels[i.level]++}if(i.motif)motifs.add(`${i.activity.id}:${norm(i.motif)}`)});let arr=Object.values(groups).filter(g=>g.total);$("#totalCount").textContent=items.length;$("#typeCount").textContent=arr.length;$("#motifCount").textContent=motifs.size;$("#csvCount").textContent=csvFiles.length;bars($("#activityBars"),arr.map(x=>({label:`${x.emoji} ${x.name}`,value:x.total})));let lv=[1,2,3,4,5].map(n=>({label:`Level ${n}`,value:arr.reduce((s,a)=>s+a.levels[n],0)}));bars($("#levelBars"),lv);$("#statsRows").innerHTML=arr.map(a=>`<tr><td><strong>${a.emoji} ${a.name}</strong></td><td>${a.total}</td>${[1,2,3,4,5].map(n=>`<td>${a.levels[n]}</td>`).join("")}</tr>`).join("");renderLegends();drawCharts();renderPlanner()}
function bars(el,data){let m=Math.max(1,...data.map(x=>x.value));el.innerHTML=data.map(x=>`<div class="barrow"><div class="barlabel">${esc(x.label)}</div><div class="bartrack"><div class="barfill" style="width:${x.value/m*100}%"></div></div><div class="barnum">${x.value}</div></div>`).join("")}
function renderLegend(selector,visibleSet,chart){
  $(selector).innerHTML=ACTIVITIES.map(a=>`<button data-act="${a.id}" data-chart="${chart}" class="${visibleSet.has(a.id)?"":"off"}"><span class="dot" style="background:${a.color}"></span>${a.name}</button>`).join("");
}
function renderLegends(){
  renderLegend("#weeklyLegend",weeklyVisible,"weekly");
  renderLegend("#monthlyLegend",monthlyVisible,"monthly");
  $$('.legend button').forEach(b=>b.onclick=()=>{
    const set=b.dataset.chart==="weekly"?weeklyVisible:monthlyVisible;
    set.has(b.dataset.act)?set.delete(b.dataset.act):set.add(b.dataset.act);
    renderLegends();drawCharts();
  });
}
function bucketData(type,end,count){let out=[];if(type==="week"){let last=monday(end);for(let i=count-1;i>=0;i--){let s=addDays(last,-7*i),p=periodInfo("week",s);out.push({label:String(isoWeek(s)),sub:s.toLocaleDateString("cs-CZ",{day:"numeric",month:"numeric"}),counts:countsFn(p),current:dateISO(s)===dateISO(monday(new Date()))})}}else{let last=new Date(end.getFullYear(),end.getMonth(),1);for(let i=count-1;i>=0;i--){let s=addMonths(last,-i),p=periodInfo("month",s);out.push({label:s.toLocaleDateString("cs-CZ",{month:"short"}),sub:String(s.getFullYear()),counts:countsFn(p),current:s.getFullYear()===new Date().getFullYear()&&s.getMonth()===new Date().getMonth()})}}return out}function countsFn(p){return counts(p)}
function drawChart(canvas,data,visibleSet,mode){
  let c=canvas.getContext("2d"),W=canvas.width,H=canvas.height,pad={l:52,r:20,t:24,b:62};
  c.clearRect(0,0,W,H);
  const active=ACTIVITIES.filter(a=>visibleSet.has(a.id));
  let max=Math.max(1,...data.map(b=>mode==="stacked"?active.reduce((sum,a)=>sum+(b.counts[a.id]||0),0):Math.max(0,...active.map(a=>b.counts[a.id]||0))));
  max=Math.ceil(max/5)*5||5;c.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--grid').trim()||"#d8e0e9";c.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted').trim()||"#667085";c.font="12px system-ui";c.textAlign="right";
  for(let i=0;i<=5;i++){let y=pad.t+(H-pad.t-pad.b)*i/5,v=Math.round(max*(5-i)/5);c.beginPath();c.moveTo(pad.l,y);c.lineTo(W-pad.r,y);c.stroke();c.fillText(v,pad.l-8,y+4)}
  let gap=5,bw=(W-pad.l-pad.r)/data.length,currentX=null;
  data.forEach((b,i)=>{let baseX=pad.l+i*bw,y=H-pad.b;if(b.current){c.fillStyle="rgba(37,99,235,.10)";c.fillRect(baseX,pad.t,bw,H-pad.t-pad.b);currentX=baseX+bw/2}
    if(mode==="stacked"){
      active.forEach(a=>{let v=b.counts[a.id]||0,h=(H-pad.t-pad.b)*v/max;if(h){c.fillStyle=a.color;c.fillRect(baseX+gap/2,y-h,Math.max(2,bw-gap),h);y-=h}});
    }else{
      const inner=Math.max(2,bw-gap),barW=active.length?inner/active.length:inner;
      active.forEach((a,j)=>{let v=b.counts[a.id]||0,h=(H-pad.t-pad.b)*v/max;if(h){c.fillStyle=a.color;c.fillRect(baseX+gap/2+j*barW,H-pad.b-h,Math.max(1,barW-1),h)}});
    }
    c.fillStyle=b.current?"#2563eb":(getComputedStyle(document.documentElement).getPropertyValue('--muted').trim()||"#667085");c.font=b.current?"bold 12px system-ui":"12px system-ui";
    if(i%(data.length>55?3:2)===0||data.length<=24||b.current){c.save();c.translate(baseX+bw/2,H-pad.b+14);c.rotate(-.55);c.textAlign="right";c.fillText(`${b.label} ${b.sub}`,0,0);c.restore()}
  });return currentX
}
function centerScroll(el,x){if(x===null||x===undefined)return;el.scrollLeft=Math.max(0,x-el.clientWidth/2)}function drawCharts(center=false){let we=addDays(new Date(),weekEndOffset*7),wd=bucketData("week",we,52),wx=drawChart($("#weeklyChart"),wd,weeklyVisible,weeklyMode);$("#weeklyRange").textContent=`${monday(addDays(we,-51*7)).toLocaleDateString("cs-CZ")} – ${addDays(monday(we),6).toLocaleDateString("cs-CZ")}`;let me=addMonths(new Date(),monthEndOffset),md=bucketData("month",me,60),mx=drawChart($("#monthlyChart"),md,monthlyVisible,monthlyMode);$("#monthlyRange").textContent=`${new Date(me.getFullYear(),me.getMonth()-59,1).toLocaleDateString("cs-CZ",{month:"long",year:"numeric"})} – ${new Date(me.getFullYear(),me.getMonth(),1).toLocaleDateString("cs-CZ",{month:"long",year:"numeric"})}`;if(center){requestAnimationFrame(()=>{centerScroll($("#weeklyScroll"),wx);centerScroll($("#monthlyScroll"),mx)})}}
function automaticTheme(){let h=new Date().getHours();return h>=7&&h<19?"light":"dark"}
function applyTheme(theme,saveChoice=false){document.documentElement.dataset.theme=theme;let b=$("#themeToggle");if(b)b.textContent=theme==="dark"?"☀️ Denní režim":"🌙 Noční režim";if(saveChoice)localStorage.setItem(THEME_KEY,theme);drawCharts()}
function initTheme(){let saved=localStorage.getItem(THEME_KEY);applyTheme(saved||automaticTheme())}
async function loadAuto(){let loaded=[];for(let src of AUTO_CSV_SOURCES){try{let r=await fetch(src,{cache:"no-store"});if(!r.ok)continue;let name=src.split('/').pop(),rows=parseCSV(await r.text());loaded.push({fileName:name,source:src,automatic:true,activity:activityForFile(name),rows})}catch{}}if(loaded.length){let names=new Set(loaded.map(x=>x.fileName.toLowerCase()));csvFiles=[...csvFiles.filter(x=>!names.has(x.fileName.toLowerCase())),...loaded];save();renderStats()}}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='stats')drawCharts(true)});$$('.period-btn').forEach(b=>b.onclick=()=>{kind=b.dataset.kind;cursor=new Date();editing=false;$$('.period-btn').forEach(x=>x.classList.toggle('active',x===b));renderPlanner()});$('#prevPeriod').onclick=()=>{cursor=shiftPeriod(kind,cursor,-1);editing=false;renderPlanner()};$('#nextPeriod').onclick=()=>{cursor=shiftPeriod(kind,cursor,1);editing=false;renderPlanner()};$('#savePlan').onclick=saveCurrentPlan;$('#editPlan').onclick=()=>{editing=true;renderPlanner()};$('#cancelEdit').onclick=()=>{editing=false;renderPlanner()};$('#archiveKind').onchange=renderArchive;
$('#csvInput').onchange=async e=>{let loaded=[];for(let f of e.target.files){loaded.push({fileName:f.name,activity:activityForFile(f.name),rows:parseCSV(await f.text()),automatic:false})}let names=new Set(loaded.map(x=>x.fileName.toLowerCase()));csvFiles=[...csvFiles.filter(x=>!names.has(x.fileName.toLowerCase())),...loaded];save();renderStats();e.target.value=""};$('#clearStats').onclick=()=>{if(confirm('Vymazat lokálně načtená CSV data?')){csvFiles=[];save();renderStats()}};
$('#weekBack').onclick=()=>{weekEndOffset-=4;drawCharts()};$('#weekForward').onclick=()=>{weekEndOffset+=4;drawCharts()};$('#weekNow').onclick=()=>{weekEndOffset=25;drawCharts(true)};$('#monthBack').onclick=()=>{monthEndOffset-=12;drawCharts()};$('#monthForward').onclick=()=>{monthEndOffset+=12;drawCharts()};$('#monthNow').onclick=()=>{monthEndOffset=29;drawCharts(true)};
$('#exportBtn').onclick=()=>{let blob=new Blob([JSON.stringify({version:2,plans,csvFiles},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vinmat-planner-${dateISO(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)};$('#importInput').onchange=async e=>{try{let d=JSON.parse(await e.target.files[0].text());plans=d.plans||{};csvFiles=d.csvFiles||[];save();renderStats();alert('Záloha byla importována.')}catch{alert('Neplatná záloha.')}e.target.value=""};
initTheme();
$$('.mode-btn').forEach(b=>b.onclick=()=>{if(b.dataset.chart==='weekly')weeklyMode=b.dataset.mode;else monthlyMode=b.dataset.mode;$$(`.mode-btn[data-chart="${b.dataset.chart}"]`).forEach(x=>x.classList.toggle('active',x===b));drawCharts()});
$('#themeToggle').onclick=()=>{let next=document.documentElement.dataset.theme==='dark'?'light':'dark';applyTheme(next,true)};
renderStats();loadAuto();